name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A comment
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: echo "hello world" > build.txt

      - uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: ./*.txt