name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  call:
    uses: tmehnert/playground-for-gh-releases/.github/workflows/build.yml@main

  release:
    runs-on: ubuntu-latest
    needs: call
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            dist/*.txt
